### ISSUE TITLE
Fix for working with ActiveRecord 3.2.0

### ISSUE THREAD

**Issue by adederer** [laserlemon/vestal_versions#80]
vestal_versions not work out of box with ActiveRecord 3.2.0 (Rails 3.2.0).
I've make following changes and all work well:
lib/vestal_versions/versions.rb
:order => "#{table_name}.#{connection.quote_column_name('number')} #{(from_number > to_number) ? 'DESC' : 'ASC'}"

--- replaced aliased_table_name to table_name

lib/vestal_versions/options.rb
class_attribute :vestal_versions_options
--- replaced class_inheritable_accessor to class_attribute

Could you please check it more carefully fix it in a trunk?

Thanks a lot! 

---

Alexander Dederer

**Comment by ZenCocoon** [comment]
Would be glad to see 3.2.x support as well

**Comment by carpeliam** [comment]
I would as well, but the last commit on this seems to be about a year old- any signs of someone maintaining vestal_versions?

**Comment by ZenCocoon** [comment]
Looks like a new maintained fork is required, anyone ? ;-)

**Comment by carpeliam** [comment]
Just looking at the network graph, it looks like there are a few forks that
address Rails 3.2 compatibility, but I haven't actually tested any of them
myself. Maybe there's already a branch that we can use. It looks like
laserlemon is active on other Github projects, any word from him on whether
he planned on dropping maintenance of the project?

2012/2/17 Sbastien Grosjean <
reply@reply.github.com

**Comment by foton** [comment]
I found fork https://github.com/alexcrichton/vestal_versions operational with Rails 3.2.8.
But unfortunately not build as gem at rubygems.org. 
I need to install it manualy, not by bundler in Rails. 
When run  "gem build vestal_versions.gemspec" I get error "undefined method `mark_version' for nil:NilClass", which I can not resolve.
    alex@alexcrichton.com

**Comment by laserlemon** [comment]
Sorry! :disappointed:

I'd love to find the most popular and best supported fork out there and either get bring it into this repo and add maintainers or to give ownership to the gem. Is there a "canonical fork" out there?

**Comment by pboling** [comment]
Fixes are in trunk, but the gem has not been released with these fixes yet.  To get it to work with rails 3.2:

```
gem 'vestal_versions', github: 'laserlemon/vestal_versions'
```

## Edit

But there is another error related to the attr_accessible still on master.  This [pull request](https://github.com/laserlemon/vestal_versions/pull/89) has a fix!

```
gem 'vestal_versions', github: 'justintanner/vestal_versions'
```
