### PR TITLE
Fix for active_record-3.2.3

### PR DESCRIPTION
**Pull request by zhangyuan**
The current vestal_versions runs into some problems and warnings with active_record-3.2.3. Here are some fixes.
- use `ActiveRecord::Relation#delete` instead of `ActiveRecord::Relation#delete_records`
- Warning from `ActiveSupport::Concern`: 

``` ruby
ActiveSupport::Deprecation.warn "The InstanceMethods module inside ActiveSupport::Concern will be no longer included automatically. Please define instance methods directly in #{self} instead."
```
- use table_name instead of aliased_table_name
- use table_name instead of set_table_name
- use sqlite3 gem instead of sqlite3-ruby in gemspec

By the way, rspec in Gemfile.lock is 2.1.0, which would not work well with Ruby-1.9.3. I've got the Error  "`run_hook_filtered': undefined method `run_all' for []:Array". see also here: https://github.com/rspec/rspec-core/issues/248 . rspec >= 2.4.0 works well.

### CODE REVIEW

**Comment by spheregenomics** [comment]
Has this fix been merged?

**Comment by dreamr** [comment]
No longer needed, however, you should notice that table_name is a property now and needs to be set via =.

self.table_name = :users

**Comment by dreamr** [comment]
Thanks for your efforts! Greatly appreciated.
