### ISSUE TITLE
Incompatible with Rails 2.1

### ISSUE THREAD

**Issue by pbyrne** [laserlemon/vestal_versions#23]
When attempting to use vestal_versions 1.0.1 in a Rails 2.1 app, the following error occurs:

`/opt/ruby-enterprise-1.8.6-20080810/lib/ruby/gems/1.8/gems/activerecord-2.1.0/lib/active_record/base.rb:1667:in`method_missing':NoMethodError: undefined method `default_scope' for #<Class:0xb0ae758>`

It appears that default_scope was added in Rails 2.3. I don't expect a fix to make this work with Rails 2.1 (vestal_versions 0.8.3 is working fine for our needs at the moment), but it would be helpful to update the gemspec to indicate that it requires Rails 2.3.

Thanks for a great gem!

**Comment by laserlemon** [comment]
Patrick, thanks for bringing that to my attention. I addressed several places in the code and tests that were making vestal_versions incompatible with Rails 2.1. I'm happy to say that they've all been addressed and vestal_versions should now work with any version of Rails since 2.1.0. I've also updated the gem dependency to reflect that requirement. Thanks again!
